spring.application.name=OrderService
#spring.config.import=configserver:http://localhost:8888

spring.config.import=configserver:http://config-server:8888
spring.profiles.active=dev

#we have added refresh actuator , we just need to call /actuator/refresh with\
#  \ post request in the postman to refresh the endpoint where we have defined @RefreshScope
