spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/JayantKumar-13/eCommerce-config-server.git
          username: ${github.username}
          password: ${github.token}
          default-label: main

server:
  port: 8888
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka


