spring.application.name=Docker_Example

spring.datasource.url=jdbc:postgresql://docker-db:5432/example-db
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
